fallback = ''

[matching]
'/.*/' = ''
'kitty' = ''
'discord' = ''
'obsidian' = ''
'/.*Oracle VM VirtualBox.*/' = ''
'Spotify' = ''
'firefox' = ''
'org.pwmt.zathura' = ''
'pcmanfm' = ''
'calibre-gui' = ''
'imv' = ''
