fallback = ''

[matching]
'/.*/' = ''
'kitty' = ''
'discord' = ''
'obsidian' = '‭ﴬ'
'/.*Oracle VM VirtualBox.*/' = ''
'Spotify' = '󰓇'
'firefox' = '󰈹'
'org.pwmt.zathura' = ''
'pcmanfm' = ''
'org.gnome.Nautilus' = ''
'calibre-gui' = ''
'imv' = ''
'Postman' = ''
'Zotero' = '󱎸'
