alias hm='cmatrix -b'
alias trash='trashy'
alias bat='batcat'
alias mandown='~/mandown/mandown'
alias lll='ll'
alias showpath='echo $PATH | tr ":" "\n"'
alias ..='cd ..'
alias dotgit='git -C ~/.dotfiles'
