#!/bin/bash

# Move to dotfiles root dir
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

# stop execution of the script immediately if a command has an error
set -e

echo ''

# shellcheck source=./link_file.sh
source $DOTFILES_ROOT/script/link_file.sh

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name "*.symlink" -not -path '.git/*' -not -path '*.ignore/*')
  do
    dst="$HOME/$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_configs () {
  info 'installing .configs'

  local overwrite_all=false backup_all=false skip_all=false

  if [ ! -d "$HOME/.config" ]; then
    mkdir "$HOME/.config"
    success "created directory $HOME/.config"
  fi

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -path "*.config" -type d -not -path '.git/*' -not -path '*.ignore/*')
  do
    dst="$HOME/.config/$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_submodules () {
  info 'installing submodules'
  git submodule update --init --recursive
}

install_dotfiles
install_configs
install_submodules

# run any other scripts named `bootstrap` (excluding this one)
for script in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name "bootstrap" -type f -not -path "*.ignore/*" -not -path "$DOTFILES_ROOT/script/bootstrap")
do
    $script
done

echo ''
echo '  All installed!'
