#!/bin/bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

# stop execution of the script immediately if a command has an error
set -e

echo ''

echo $DOTFILES_ROOT

# output messages
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_file () {
	local src=$1 dst=$2

	local overwrite= backup= skip=
	local action=

  # if destination file exists, or exists and is a directory, or exists and is a symlink
	if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      # if pointing to the same location we want it to
      if [ "$currentSrc" == "$src" ]
      then
        skip=true
      else
        user "File already exists: $dst ($basename "$src")), what do you want to do\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi
    fi

    # if overwrite is unset, set it to value of overwrite_all
    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  # if not skipping this file
  if [ "$skip" != "true" ] # "false" or empty
  then
    ln -s "$src" "$dst"
    success "linked $src to $dst"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name "*.symlink" -not -path '.git/*' -not -path '*.ignore/*')
  do
    dst="$HOME/$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_configs () {
  info 'installing .configs'

  local overwrite_all=false backup_all=false skip_all=false

  if [ ! -d "$HOME/.config" ]; then
    mkdir "$HOME/.config"
    success "created directory $HOME/.config"
  fi

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -path "*.config" -type d -not -path '.git/*' -not -path '*.ignore/*')
  do
    dst="$HOME/.config/$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_submodules () {
  info 'installing submodules'
  git submodule update --init --recursive
}

install_dotfiles
install_configs
install_submodules

echo ''
echo '  All installed!'
