#!/usr/bin/env bash

# Select a dir for the session
if [ $# -eq 1 ]; then
    selected=$1
else
    selected=$((find ~/PROJECTS ~/UNI ~/OPEN-SOURCE -mindepth 1 -maxdepth 2 -type d; \
                find ~/ ~/.dotfiles ~/UNI/II/00-project ~/Documents -mindepth 1 -maxdepth 1 -type d) \
                | fzf)
fi

if [[ "$selected" = "" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)

# If tmux isn't already running
if [[ "$TMUX" = "" && "$tmux_running" = "" ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

# Check if the selected dir already has a matching tmux session
if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    # -d: don't attach session to current terminal
    tmux new-session -ds "$selected_name" -c "$selected"
fi

client_running=$(tmux list-clients)

if [[ "$client_running" = "" ]]; then
    tmux attach -t "$selected_name"
    exit 0
fi

tmux switch-client -t "$selected_name"
