#!/usr/bin/env bash

languages=$(echo "rust javascript typescript python c lua bash html css" | tr " " "\n")
commands=$(echo "find man tldr sed awk tr cp ls grep xargs git echo printf" | tr " " "\n")

selected=$(printf "$languages\n$commands" | fzf)

read -p "Query: " query

# Escape spaces in query string
query=$(echo "$query" | tr " " "+")

# Curl the corresponding format depending if selection is a language or command
if echo "$languages" | grep -q "$selected"; then
    tmux neww bash -c "curl -s cht.sh/$selected/$query | less -R"
else
    tmux neww bash -c "curl -s cht.sh/$selected~$query | less -R"
fi
