#!/bin/bash
# This should be run from inside a git repo

if [ ! -d ".git" ]; then
    echo "Error: must be run from the root of a Git repository."
    exit 1
fi

# check that it's a personal repo (ie the remote is to my github/gitlab)
CONTAINS_MRW=$(cat .git/config | grep -E "(martin)|(mrw)")
if [ "$CONTAINS_MRW" = "" ]; then
    # ignore non-personal repos
    exit 0
fi

REPO_NAME=$(basename "$PWD")

DIRTY=false

UNCOMMITTED=$(git status --porcelain)

if [ "$UNCOMMITTED" != "" ]; then
    echo "$(tput bold)$REPO_NAME$(tput sgr0) has uncommitted changes."
    DIRTY=true
fi

AHEAD=$(git status --porcelain -b | grep "ahead")

if [ "$AHEAD" != "" ]; then
    echo "$(tput bold)$REPO_NAME$(tput sgr0) has unpushed commits."
    DIRTY=true
fi

if [ "$DIRTY" = true ]; then
    # print repo path relative to ~
    echo -e "    \033[0;35m$(dirs +0)\033[0m"
fi
